SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE purchase_lines;
TRUNCATE TABLE purchases;
TRUNCATE TABLE game_author;
TRUNCATE TABLE games;
TRUNCATE TABLE authors;
TRUNCATE TABLE publishers;
TRUNCATE TABLE categories;
TRUNCATE TABLE users;

SET REFERENTIAL_INTEGRITY TRUE;