SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE game_author;
TRUNCATE TABLE games;
TRUNCATE TABLE authors;
TRUNCATE TABLE publishers;
TRUNCATE TABLE categories;
TRUNCATE TABLE users;

SET REFERENTIAL_INTEGRITY TRUE;